.TH "LDMS DAEMON" 1 "2021-06-02" "1.0"
.SH NAME
ldmsd – anti-forensics dead man's switch daemon

.SH SYNOPSIS
.B ldmsd
[\fIoptions\fR]

.SH DESCRIPTION
Daemon program.
Daemon uses the gnu c library's
.BR syslog(3)
function for saving logs.
Log file location and the method to read it depends on your setup.
For example if you have systemd, you can use following command:
\fBjournalctl -f _COMM=ldms\fR.

.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR
show help
.TP
\fB-v\fR, \fB--version\fR
show version
.TP
\fB-c\fR, \fB--config\fR
config file location

.SH SEE ALSO
.BR ldms(1)
.BR ldmsd.conf(5)

.SH AUTHOR
Noa-Emil Nissinen

.SH BUGS
https://gitlab.com/4shadoww/ldms
