.TH "LDMS DAEMON" 1 "2021-05-29" "1.0"
.SH NAME
ldmsd – anti-forensics dead man's switch daemon

.SH SYNOPSIS
.B ldmsd
[\fIoptions\fR]

.SH DESCRIPTION
Daemon program.

.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR
show help
.TP
\fB-v\fR, \fB--version\fR
show version
.TP
\fB-c\fR, \fB--config\fR
config file location

.SH SEE ALSO
.BR ldms(1)
.BR ldmsd.conf(7)

.SH AUTHOR
Noa-Emil Nissinen

.SH BUGS
https://gitlab.com/4shadoww/ldms
